# Junwoo Jang - CS4352 Project1

CC=gcc
CFLAGS= -Wall -Wextra -std=c99

all: chain tree

chain:
	$(CC) $(CFLAGS) chain.c -o chain 

tree:
	$(CC) $(CFLAGS) tree.c -o tree 

clean:
	rm -rf chain tree testcases
